seed: 0

data:
  path: "data/waimai_10k.csv"
  batch_size: 8
  vocabulary_size: 100

model:
  name: "textcnn"
  n_chanel: 1
  n_classes: 2
  n_filter: 2
  dropout: 0.2
  filter_sizes : [2,3]
  embedding_dim : 100

  optimizer:
    lr: 3e-4

trainer:
  gpus: 0
  max_epochs: 10

defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog